"""Create a source and copyable loader without reading/pasting helper boilerplate."""
import argparse
import ast
import sys
from pathlib import Path
from make_loader import make_loader, validate_rhino_path

ASSETS = Path(__file__).resolve().parents[1] / 'assets'


def build_source(example):
    starter = (ASSETS / 'component_starter.py').read_text(encoding='utf-8')
    if example == 'tree':
        return starter
    if example != 'curve-divide':
        raise ValueError('Unknown example: ' + example)
    body = (ASSETS / 'curve_divide_body.py').read_text(encoding='utf-8')
    body = body.replace(
        'Build with scripts/create_component.py --example curve-divide; the generator\n'
        'embeds the shared port helpers to produce one standalone development source.',
        'Standalone development source generated by create_component.py.\n'
        'All port helpers are embedded; the skill folder is not a runtime dependency.')
    # The starter owns all infrastructure. AST extraction avoids a second maintained copy.
    helpers = [ast.get_source_segment(starter, n) for n in ast.parse(starter).body
               if isinstance(n, ast.FunctionDef) and n.name not in ('_process_tree', '_run_component')]
    module = ast.parse(body)
    doc = module.body[0]
    lines = body.splitlines(keepends=True)
    result = (''.join(lines[:doc.end_lineno]) + '\n\n' + '\n\n'.join(helpers)
              + '\n\n' + ''.join(lines[doc.end_lineno:]))
    ast.parse(result)
    return result


def create(source, example='curve-divide', rhino_source=None):
    validate_rhino_path(rhino_source)
    source = Path(source).expanduser().resolve()
    if source.suffix.lower() != '.py':
        raise ValueError('Destination must end in .py')
    loader = source.with_name(source.stem + '_loader.py')
    if source.exists() or loader.exists():
        raise FileExistsError('Source or loader already exists; edit the existing source or choose a new path.')
    code = build_source(example)
    source.parent.mkdir(parents=True, exist_ok=True)
    source.write_text(code, encoding='utf-8')
    load_code = make_loader(source, rhino_source=rhino_source)
    loader.write_text(load_code, encoding='utf-8')
    return source, loader, load_code


def main():
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(encoding='utf-8')
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', type=Path)
    parser.add_argument('--example', choices=['tree', 'curve-divide'], default='curve-divide')
    parser.add_argument('--rhino-source', help='Explicit path on the Rhino host; agent host cannot verify it')
    args = parser.parse_args()
    source, loader, code = create(args.source, args.example, args.rhino_source)
    print('Source: %s\nLoader: %s\n' % (source, loader))
    print(code, end='')


if __name__ == '__main__':
    main()
